services:
  web:
    image: sse
    build:
      context: .
    volumes:
      - /home/moebius/sse.sqlite3:/app/sse.sqlite3
      - ./sse:/app/sse
    entrypoint: /app/entrypoint.sh
    depends_on:
      - redis
  redis:
    image: redis:alpine
  nginx:
    image: nginx:latest
    ports:
      - "8000:8080"
    volumes:
      - ./static/:/var/www/static/
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
